wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: step
      6:
      - 3
    - 1: epoch
      6:
      - 3
    - 1: batch_training_loss
      5: 1
      6:
      - 1
      - 3
    - 1: epoch_training_loss
      5: 2
      6:
      - 1
      - 3
    - 1: trainer/global_step
      6:
      - 3
    - 1: pred_imgs._type
      5: 5
      6:
      - 1
    - 1: pred_imgs.width
      5: 5
      6:
      - 1
    - 1: pred_imgs.height
      5: 5
      6:
      - 1
    - 1: pred_imgs.format
      5: 5
      6:
      - 1
    - 1: pred_imgs.count
      5: 5
      6:
      - 1
    - 1: pred_imgs.captions
      5: 5
      6:
      - 1
    - 1: epoch_validation_ENS
      5: 5
      6:
      - 1
    - 1: epoch_validation_mad
      5: 5
      6:
      - 1
    - 1: epoch_validation_ssim
      5: 5
      6:
      - 1
    - 1: epoch_validation_ols
      5: 5
      6:
      - 1
    - 1: epoch_validation_emd
      5: 5
      6:
      - 1
    - 1: lr
      5: 5
      6:
      - 1
    python_version: 3.7.1
    start_time: 1642316343
    t:
      1:
      - 1
      - 9
      3:
      - 16
      4: 3.7.1
      5: 0.12.9
      8:
      - 5
cfg/data/mesoscale_cut:
  desc: null
  value:
  - 39
  - 41
cfg/data/pickle_dir:
  desc: null
  value: Data/all_data_5
cfg/model/baseline:
  desc: null
  value: last_frame
cfg/model/big_mem:
  desc: null
  value: true
cfg/model/dilation_rate:
  desc: null
  value: 1
cfg/model/future_training:
  desc: null
  value: 20
cfg/model/hidden_channels:
  desc: null
  value: 20
cfg/model/img_height:
  desc: null
  value: 128
cfg/model/img_width:
  desc: null
  value: 128
cfg/model/input_channels:
  desc: null
  value: 11
cfg/model/kernel:
  desc: null
  value: 5
cfg/model/layer_norm:
  desc: null
  value: false
cfg/model/memory_kernel:
  desc: null
  value: 5
cfg/model/n_layers:
  desc: null
  value: 3
cfg/model/output_channels:
  desc: null
  value: 4
cfg/training/accelerator:
  desc: null
  value: auto
cfg/training/devices:
  desc: null
  value: 1
cfg/training/epochs:
  desc: null
  value: 200
cfg/training/gpus:
  desc: null
  value: 1
cfg/training/lr_factor:
  desc: null
  value: 0.1
cfg/training/lr_threshold:
  desc: null
  value: 0.001
cfg/training/num_workers:
  desc: null
  value: 0
cfg/training/offline:
  desc: null
  value: false
cfg/training/optimizer:
  desc: null
  value: adamW
cfg/training/patience:
  desc: null
  value: 100
cfg/training/print_predictions:
  desc: null
  value: true
cfg/training/seed:
  desc: null
  value: 1
cfg/training/start_learn_rate:
  desc: null
  value: 0.0003
cfg/training/test_loss:
  desc: null
  value: ENS
cfg/training/train_batch_size:
  desc: null
  value: 4
cfg/training/training_loss:
  desc: null
  value: l2
cfg/training/use_context:
  desc: null
  value: false
cfg/training/val_1_batch_size:
  desc: null
  value: 4
cfg/training/val_2_batch_size:
  desc: null
  value: 4
data:
  desc: null
  value:
    mesoscale_cut:
    - 39
    - 41
    pickle_dir: Data/all_data_5
model:
  desc: null
  value:
    baseline: last_frame
    big_mem: true
    dilation_rate: 1
    future_training: 20
    hidden_channels: 20
    img_height: 128
    img_width: 128
    input_channels: 11
    kernel: 5
    layer_norm: false
    memory_kernel: 5
    n_layers: 3
    output_channels: 4
training:
  desc: null
  value:
    accelerator: auto
    checkpoint: wandb/run-20220113_204500-2nq3gfum/files/runtime_model/model_epoch=007.ckpt
    devices: 1
    epochs: 200
    gpus: 1
    lr_factor: 0.1
    lr_threshold: 0.001
    num_workers: 0
    offline: false
    optimizer: adamW
    patience: 100
    print_predictions: true
    seed: 1
    start_learn_rate: 0.0003
    test_loss: ENS
    train_batch_size: 4
    training_loss: l2
    use_context: false
    val_1_batch_size: 4
    val_2_batch_size: 4
